import Link from "next/link";

export const metadata = {
  title: "Terms of Service | Decision Lab",
  description:
    "Terms and conditions for using Decision Lab decision simulations.",
};

export default function TermsPage() {
  return (
    <main className="stage-bg min-h-screen px-4 py-6 sm:px-10 sm:py-10">
      <section className="panel-shell mx-auto max-w-4xl bg-[#fffff5] px-6 py-10 sm:px-10">
        <h1 className="display-font mb-6 text-4xl font-bold uppercase text-[#1d2440]">Terms of Service</h1>
        <p className="mb-6 text-sm text-[#6a7b9d]">Effective date: February 22, 2026</p>

        <p className="mb-6 text-[#4f5e7c]">
          By accessing or using Decision Lab, you agree to these Terms of Service. If you do not agree,
          you should discontinue use of the service.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Informational Use Only</h2>
        <p className="mb-6 text-[#4f5e7c]">
          Decision Lab provides informational simulation outputs. Content generated by the service does not
          constitute legal, medical, financial, therapeutic, or other regulated professional advice.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">User Responsibility</h2>
        <p className="mb-6 text-[#4f5e7c]">
          Users remain solely responsible for all decisions and actions taken based on service outputs.
          You should independently validate critical assumptions before making high-impact decisions.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Acceptable Use</h2>
        <p className="mb-6 text-[#4f5e7c]">
          You agree not to misuse the platform, interfere with system integrity, attempt unauthorized access,
          submit unlawful content, or use automated methods to degrade service reliability.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Intellectual Property</h2>
        <p className="mb-6 text-[#4f5e7c]">
          Unless otherwise stated, platform design, structure, and original site content are owned by
          Decision Lab and protected by applicable intellectual property laws.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Service Availability and Changes</h2>
        <p className="mb-6 text-[#4f5e7c]">
          We may update, suspend, or discontinue any part of the service at any time for maintenance,
          security, legal, or product reasons. We do not guarantee uninterrupted or error-free operation.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Limitation of Liability</h2>
        <p className="mb-6 text-[#4f5e7c]">
          To the maximum extent permitted by law, Decision Lab is not liable for indirect, incidental,
          consequential, or special damages arising from use of the service or reliance on its outputs.
        </p>

        <h2 className="mb-3 text-2xl font-semibold text-[#1d2440]">Updates to These Terms</h2>
        <p className="text-[#4f5e7c]">
          We may revise these Terms from time to time. Continued use after updates constitutes acceptance
          of the revised terms.
        </p>
        <p className="mt-4">
          <Link href="/" className="text-[#4f5e7c] underline decoration-[#80caff] underline-offset-2">
            Back to Home
          </Link>
        </p>
      </section>
    </main>
  );
}
